apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: 'registry.redhat.io/redhat/redhat-operator-index:v4.20'
  grpcPodConfig:
    extractContent:
      cacheDir: /tmp/cache
      catalogDir: /configs
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 120m