apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: mysql-root/password
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: app-key
      remoteRef:
        key: laravel-app-key/password
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: backpack-license
      remoteRef:
        key: backpack-license-key/password
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: mysql-website_backend2-password
      remoteRef:
        key: mysql-website_backend2/password
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None