apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: Verseghy
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-token-verseghy
          key: token
