apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: ghcr.io/verseghy/website_backend2
    newTag: 5f56ae8cc7cc8acc68ce8250c1a3c1feeb1f3381
    newName: ghcr.io/verseghy/website_backend2
