apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: ghcr.io/verseghy/website_backend2
    newTag: d1c80711c4d544bdf6bb935d9f3b34b388ac85a9
    newName: ghcr.io/verseghy/website_backend2
