apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: ghcr.io/verseghy/website_backend2
    newTag: da187ebdac103cba8f9e9f773648bb5b6dcd886c
    newName: ghcr.io/verseghy/website_backend2
