apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: website-static
  title: Website Static Assets
  description: nginx serving /docs and /images under verseghy-gimnazium.net
  annotations:
    github.com/project-slug: Verseghy/website_static
    argocd/instance-name: verseghy
    argocd/app-selector: verseghy.net/component=static
    backstage.io/source-location: url:https://github.com/Verseghy/website_static/tree/master/
  tags:
    - website
    - nginx
spec:
  type: website
  lifecycle: production
  owner: group:verseghy
  system: verseghy-website
