apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: cert
      remoteRef:
        key: prow-github-token/cert
    - secretKey: appid
      remoteRef:
        key: prow-github-token/appid
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hmac-token
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: hmac
      remoteRef:
        key: prow-hmac-token/hmac
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-creds
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: prow-minio-root-creds/user
    - secretKey: password
      remoteRef:
        key: prow-minio-root-creds/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      data:
        service-account.json: |
          {
            "region": "minio",
            "access_key": "{{ .user }}",
            "endpoint": "minio.verseghy.svc.cluster.local",
            "insecure": true,
            "s3_force_path_style": true,
            "secret_key": "{{ .password }}"
          }
  data:
    - secretKey: user
      remoteRef:
        key: prow-minio-root-creds/user
    - secretKey: password
      remoteRef:
        key: prow-minio-root-creds/password
