apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      data:
        GITHUB_APP_ID: "{{ .app_id }}"
        GITHUB_APP_CLIENT_ID: "{{ .client_id }}"
        GITHUB_APP_CLIENT_SECRET: "{{ .client_secret }}"
        GITHUB_APP_PRIVATE_KEY: "{{ .private_key }}"
  data:
    - secretKey: app_id
      remoteRef:
        key: rhdh-github-app/app_id
    - secretKey: client_id
      remoteRef:
        key: rhdh-github-app/client_id
    - secretKey: client_secret
      remoteRef:
        key: rhdh-github-app/client_secret
    - secretKey: private_key
      remoteRef:
        key: rhdh-github-app/private_key
