apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: Server
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-token
          key: token
