apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ssr
  template:
    metadata:
      labels:
        app: frontend-ssr
    spec:
      containers:
        - name: app
          image: verseghy/website_frontend
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 300
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            timeoutSeconds: 15
          resources:
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ssr-svc
spec:
  selector:
    app: frontend-ssr
  ports:
    - name: frontend-ssr
      protocol: TCP
      port: 80
      targetPort: 4000
