apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: backend-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: mysql-root/password