apiVersion: v1
kind: ServiceAccount
metadata:
  name: anyuid
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anyuid
subjects:
  - kind: ServiceAccount
    name: anyuid
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io