apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: ghcr.io/verseghy/website_frontend
    newTag: e13ea780a9d4375b164acc98985cf9254526d090
    newName: ghcr.io/verseghy/website_frontend
