apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: ghcr.io/verseghy/website_frontend
    newTag: 724f30f70fec5bff7c1287f7dd7dc0b38def6a75
